### ISSUE TITLE
Add Azure DevOps Task to install NLU.DevOps extension

### ISSUE THREAD

**Issue by rozele** [microsoft/NLU.DevOps#126]
Add a task called `NLUInstallExtension` that will install a .NET Core CLI tool package in the correct location for integration with NLU.DevOps.

**Comment by rozele** [comment]
Not sure this is needed as it's reasonably trivial to just use:
```
- task: DotNetCoreCLI@2
  displayName: Install dotnet-nlu-mock
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-nlu-mock --add-source $(Build.ArtifactStagingDirectory) --tool-path $(Agent.TempDirectory)/.dotnet
```
