### ISSUE TITLE
Update benchmark command to check for performance regressions

### ISSUE THREAD

**Issue by rozele** [microsoft/NLU.DevOps#278]
In addition to merely printing the F-measure comparison between builds, add functionality to report performance regressions, e.g., with the test settings.
```json
{
  "trueNegativeIntent": "None",
  "thresholds": [
    {
      "type": "intent",
      "threshold": 0.1
    },
    {
      "type": "entity",
      "threshold": 0.1
    },
    {
      "type": "intent",
      "group": "PlayMusic",
      "threshold": 0.0
    },
    {
      "type": "entity",
      "group": "Genre",
      "threshold": 0.0
    }
  ]
}
```

We could also consider adding support for YAML:
```yaml
trueNegativeIntent: None
thresholds:
- type: intent
  threshold: 0.1
- type: entity
  threshold: 0.1
- type: intent
  group: PlayMusic
  threshold: 0.0
- type: entity
  group: Genre
  threshold: 0.0
```
