### ISSUE TITLE
Add absolute thresholds for performance benchmarks in compare command

### ISSUE THREAD

**Issue by rozele** [microsoft/NLU.DevOps#312]
Currently, the `compare` command only supports checking against a baseline (e.g., previous compare run). It would be useful to add absolute statistics, e.g., saying that the F<sub>1</sub> score exceeds some absolute value. For example:
```
thresholds:
- type: intent
  group: PlayMusic
  threshold: 0.9
  comparison: absolute|relative
```

For backward compatibility, relative should be the default value.
