### ISSUE TITLE
Allow customization of comparison metric for performance regression

### ISSUE THREAD

**Issue by rozele** [microsoft/NLU.DevOps#313]
The `compare` command performance regression functionality currently only works for F<sub>1</sub> scores. We should allow thresholds to be set for precision, recall or arbitrary F-scores. For example, you should be able to specify in the compare test settings:
```yaml
thresholds:
- type: intent
  group: PlayMusic
  threshold: 0.1
  metric: recall
```
Or:
```yaml
thresholds:
- type: intent
  group: PlayMusic
  threshold: 0.1
  metric: f0.5
```

The default metric should be F<sub>1</sub>.
